"use client";

import { useEffect, useState, useRef } from "react";
import { fetchStockAnalysis, searchCompanies, StockAnalysisResponse, TickerInfo } from "@/lib/api";

export default function ReportsPage() {
  const [activeSymbol, setActiveSymbol] = useState("AAPL");
  const [searchQuery, setSearchQuery] = useState("");
  const [searchResults, setSearchResults] = useState<TickerInfo[]>([]);
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const [reportData, setReportData] = useState<StockAnalysisResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const dropdownRef = useRef<HTMLDivElement>(null);

  // Load last searched symbol on mount
  useEffect(() => {
    const lastSymbol = localStorage.getItem("marketmind_last_symbol");
    if (lastSymbol) {
      setActiveSymbol(lastSymbol);
    }
  }, []);

  // Fetch live analysis report whenever activeSymbol changes
  useEffect(() => {
    if (!activeSymbol) return;
    setLoading(true);
    setError(null);

    fetchStockAnalysis(activeSymbol)
      .then((data) => setReportData(data))
      .catch((err) => setError(err.message || "Failed to load report data"))
      .finally(() => setLoading(false));
  }, [activeSymbol]);

  // Live auto-recommendation search logic as user types
  useEffect(() => {
    if (!searchQuery.trim()) {
      setSearchResults([]);
      setIsDropdownOpen(false);
      return;
    }

    const timer = setTimeout(async () => {
      try {
        const results = await searchCompanies(searchQuery);
        setSearchResults(results);
        setIsDropdownOpen(true);
      } catch (err) {
        console.error("Company recommendation search failed", err);
      }
    }, 250);

    return () => clearTimeout(timer);
  }, [searchQuery]);

  // Close recommendations dropdown when clicking outside
  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
        setIsDropdownOpen(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  const handleSelectCompany = (symbol: string) => {
    setActiveSymbol(symbol.toUpperCase());
    setSearchQuery("");
    setIsDropdownOpen(false);
  };

  const handleSearchSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (searchQuery.trim()) {
      setActiveSymbol(searchQuery.trim().toUpperCase());
      setSearchQuery("");
      setIsDropdownOpen(false);
    }
  };

  const downloadReport = (data: StockAnalysisResponse) => {
    const reportText = `
===================================================================
MARKETMIND AI - INSTITUTIONAL RESEARCH DOSSIER
Generated Date: ${new Date().toLocaleString()}
===================================================================

1. EXECUTIVE OVERVIEW
-------------------------------------------------------------------
Symbol:             ${data.symbol}
Company Name:       ${data.name}
Current Price:      ₹${data.overview.current_price.toLocaleString()}
Period Change:      ${data.overview.period_change_pct}%
Period High:        ₹${data.overview.period_high.toLocaleString()}
Period Low:         ₹${data.overview.period_low.toLocaleString()}

2. AI MODEL FORECAST & DECISION INTELLIGENCE
-------------------------------------------------------------------
Overall AI Score:   ${data.ai_score} / 100
Decision Signal:    ${data.signal}
Signal Reason:      ${data.signal_reason}
Predicted Target:   ${data.predicted_price ? `₹${data.predicted_price.toLocaleString()}` : "N/A"}

3. RISK & VOLATILITY DIAGNOSTICS
-------------------------------------------------------------------
Risk Label:         ${data.risk_label}
Risk Index Score:   ${data.risk_score} / 100
Annualized Volatility: ${data.indicators.volatility_pct}%

4. TECHNICAL INDICATORS
-------------------------------------------------------------------
RSI (14-Day):       ${data.indicators.rsi?.toFixed(2) ?? "N/A"}
MACD Line:          ${data.indicators.macd?.toFixed(2) ?? "N/A"}
MACD Signal:        ${data.indicators.macd_signal?.toFixed(2) ?? "N/A"}

5. SHAP EXPLAINABILITY DRIVERS
-------------------------------------------------------------------
${data.explainability
  .map(
    (item) =>
      `- ${item.feature}: ${((item as any).contribution ?? (item as any).importance ?? 0).toFixed(4)}`
  )
  .join("\n")}

===================================================================
Disclaimer: Confidential financial intelligence generated by MarketMind AI engine.
    `.trim();

    const blob = new Blob([reportText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${data.symbol}_MarketMind_Research_Report.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 max-w-5xl">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-white tracking-tight">Dynamic Research Reports</h1>
          <p className="text-xs text-[#8b90a3] mt-1">
            Generate and export live institutional dossiers, SHAP explainability breakdowns, and ML model audits
          </p>
        </div>

        {/* Custom Report Search Input with Live Recommendations Dropdown */}
        <div className="relative w-full md:w-80" ref={dropdownRef}>
          <form onSubmit={handleSearchSubmit} className="flex gap-2">
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search ticker (e.g. AA, NVDA, TCS)..."
              className="bg-[#0d1117] border border-[#2d333b] rounded-xl px-3 py-2 text-xs text-white placeholder-[#8b90a3] focus:outline-none focus:border-[#0fa3b1] w-full"
            />
            <button
              type="submit"
              className="bg-[#0fa3b1] hover:bg-[#06c8d9] text-black font-bold text-xs px-4 py-2 rounded-xl transition-colors shrink-0"
            >
              Generate
            </button>
          </form>

          {/* Recommended Companies Dropdown Menu */}
          {isDropdownOpen && searchResults.length > 0 && (
            <div className="absolute top-full left-0 right-0 mt-2 bg-[#161b22] border border-[#2d333b] rounded-xl shadow-2xl overflow-hidden z-50 max-h-60 overflow-y-auto">
              {searchResults.map((item) => (
                <button
                  key={item.symbol}
                  onClick={() => handleSelectCompany(item.symbol)}
                  className="w-full text-left px-3 py-2.5 hover:bg-[#0d1117] border-b border-[#2d333b]/50 last:border-0 flex items-center justify-between transition-colors"
                >
                  <div>
                    <span className="text-xs font-bold text-white block">{item.symbol}</span>
                    <span className="text-[10px] text-[#8b90a3] block truncate">{item.name}</span>
                  </div>
                  <span className="text-[10px] text-[#06c8d9] font-mono bg-[#0fa3b1]/10 px-2 py-0.5 rounded">
                    {item.exchange}
                  </span>
                </button>
              ))}
            </div>
          )}
        </div>
      </div>

      {loading ? (
        <div className="h-64 bento-card flex flex-col items-center justify-center gap-3">
          <div className="w-8 h-8 border-2 border-[#0fa3b1] border-t-transparent rounded-full animate-spin" />
          <span className="text-xs text-[#8b90a3]">Compiling research dossier for {activeSymbol}...</span>
        </div>
      ) : error || !reportData ? (
        <div className="p-6 bento-card border-[#ff5366]/30 text-center">
          <p className="text-sm text-[#ff5366] font-bold">Failed to load report for {activeSymbol}</p>
          <p className="text-xs text-[#8b90a3] mt-1">{error}</p>
        </div>
      ) : (
        <div className="bento-card space-y-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-[#2d333b] pb-4">
            <div>
              <span className="text-xs font-bold text-[#06c8d9] bg-[#0fa3b1]/10 px-2.5 py-1 rounded-md uppercase tracking-wider">
                Live Active Dossier
              </span>
              <h2 className="text-xl font-black text-white mt-2">
                {reportData.name} ({reportData.symbol}) Analysis Report
              </h2>
              <p className="text-xs text-[#8b90a3] mt-0.5">
                Generated: {new Date().toLocaleDateString()} • AI Score: {reportData.ai_score}/100
              </p>
            </div>

            <button
              onClick={() => downloadReport(reportData)}
              className="bg-[#0fa3b1] hover:bg-[#06c8d9] text-black font-extrabold text-xs px-5 py-2.5 rounded-xl transition-all shadow-lg shadow-[#0fa3b1]/10 flex items-center justify-center gap-2"
            >
              <span>↓</span> Download Summary Report
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="p-4 bg-[#0d1117] border border-[#2d333b] rounded-xl">
              <span className="text-[10px] text-[#8b90a3] uppercase font-bold block">Current Price</span>
              <span className="text-lg font-black text-white mt-1 block">
                ₹{reportData.overview.current_price.toLocaleString()}
              </span>
            </div>

            <div className="p-4 bg-[#0d1117] border border-[#2d333b] rounded-xl">
              <span className="text-[10px] text-[#8b90a3] uppercase font-bold block">Decision Signal</span>
              <span className="text-lg font-black text-[#06c8d9] mt-1 block">
                {reportData.signal}
              </span>
            </div>

            <div className="p-4 bg-[#0d1117] border border-[#2d333b] rounded-xl">
              <span className="text-[10px] text-[#8b90a3] uppercase font-bold block">Risk Rating</span>
              <span className="text-lg font-black text-[#00d084] mt-1 block">
                {reportData.risk_label}
              </span>
            </div>
          </div>

          <div className="p-4 bg-[#0d1117] border border-[#2d333b] rounded-xl space-y-2">
            <span className="text-xs font-bold text-[#8b90a3] uppercase block">AI Executive Summary</span>
            <p className="text-xs text-white leading-relaxed">{reportData.signal_reason}</p>
          </div>
        </div>
      )}
    </div>
  );
}