"""Initial schema migration

Revision ID: d3d775ee57f9
Revises: None
Create Date: 2026-09-12 21:03:58.669208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd3d775ee57f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_holdings_id'), table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_index(op.f('ix_investment_simulations_id'), table_name='investment_simulations')
    op.drop_table('investment_simulations')
    op.drop_index(op.f('ix_saved_analyses_id'), table_name='saved_analyses')
    op.drop_table('saved_analyses')
    op.add_column('portfolios', sa.Column('symbol', sa.String(), nullable=False))
    op.add_column('portfolios', sa.Column('shares', sa.Float(), nullable=False))
    op.add_column('portfolios', sa.Column('avg_price', sa.Float(), nullable=False))
    op.drop_column('portfolios', 'name')
    op.drop_column('users', 'is_active')
    op.create_index(op.f('ix_watchlists_symbol'), 'watchlists', ['symbol'], unique=False)
    op.drop_column('watchlists', 'company_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlists', sa.Column('company_name', sa.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_watchlists_symbol'), table_name='watchlists')
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.add_column('portfolios', sa.Column('name', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('portfolios', 'avg_price')
    op.drop_column('portfolios', 'shares')
    op.drop_column('portfolios', 'symbol')
    op.create_table('saved_analyses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ai_score', sa.INTEGER(), nullable=False),
    sa.Column('signal', sa.VARCHAR(length=50), nullable=False),
    sa.Column('risk_label', sa.VARCHAR(length=50), nullable=False),
    sa.Column('predicted_price', sa.FLOAT(), nullable=True),
    sa.Column('analysis_data', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_analyses_id'), 'saved_analyses', ['id'], unique=False)
    op.create_table('investment_simulations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=50), nullable=False),
    sa.Column('mode', sa.VARCHAR(length=20), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('period_years', sa.INTEGER(), nullable=False),
    sa.Column('expected_return_pct', sa.FLOAT(), nullable=False),
    sa.Column('future_value', sa.FLOAT(), nullable=False),
    sa.Column('total_invested', sa.FLOAT(), nullable=False),
    sa.Column('estimated_gain', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_simulations_id'), 'investment_simulations', ['id'], unique=False)
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=50), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('avg_buy_price', sa.FLOAT(), nullable=False),
    sa.Column('added_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_holdings_id'), 'portfolio_holdings', ['id'], unique=False)
    # ### end Alembic commands ###